//MIDI CC control numbers
//These broadly follow standard CC assignments
#define   CCmodwheel  1 //pitch LFO amount - less from mod wheel
#define   CCLfoDepth  3 //pitch LFO amount - panel control

#define   CCfx_Bypass 4
#define   CCglideTime 5
#define   CCdco_at_SW 6
#define   CCvolumeControl 7
#define   CCfilterA 8
#define   CCfilterB 9
#define   CCamDepth 11
#define   CCosc2Interval 12
#define   CCfilter_at_SW 13
#define   CCATDepth 14
#define   CCfmDepth 15
#define   CCosc1PW 16
#define   CCosc2PW 17
#define   CCosc1PWM 18
#define   CCosc2PWM 19
#define   CCmodWheelDepth 20
#define   CCvcaGate 21
#define   CCfilterLFO 22
#define   CCnoiseLevel 23
#define   CCfilterPoleSW 24
#define   CCfilterLevel2 25
#define   CCfilterLevel1 26
#define   CCFilterLoop 27
#define   CCAmpLoop 28
#define   CCosc2envPWM 29
#define   CCkeyTrack 30
#define   CCkeyTrackSW 31
#define   CCwholemode 32
#define   CCdualmode 33
#define   CCsplitmode 34
#define   CCeffectNumSW 35
#define   CCeffectBankSW 36
#define   CCmonoMulti 37
#define   CCnoiseSrc 38
#define   CCfilterType 39
#define   CClfo1retrig 40
#define   CCosc2EnvDepth 41
#define   CCvcaVel 42
#define   CCfilterVel 43
#define   CCfilterRelease 44
#define   CCfilterAttack 45
#define   CCfilterSustain 46
#define   CCfilterDecay 47
#define   CCfilterLevel 48
#define   CCosc1sawCount 49
#define   CCfilterEGinv 50
#define   CCosc1sawDetune 51
#define   CCfilterEGlevel 53
#define   CCkeyboardMode 54
#define   CCNotePriority 55
#define   CCarpRate 56
#define   CCampRelease 57
#define   CCampAttack 58
#define   CCampSustain 59
#define   CCampDecay 60
#define   CCosc2TriangleLevel 61
#define   CCosc1SubLevel 62
#define   CCLFO1Delay 63

#define   CCglideSW 65
#define   CCPitchBend 66
#define   CCMWDepth 67
#define   CCosc1PulseLevel 68
#define   CCosc1SawLevel 69
#define   CCLFO1Slope 70
#define   CCosc2Detune 71
#define   CCLFO3Rate 72
#define   CCLFO3Delay 73
#define   CCfilterCutoff 74
#define   CCosc1envPWM 75
#define   CClfoAlt 76
#define   CCLFO1Rate 77
#define   CClfoMult 78
#define   CCLFO2Waveform 79
#define   CCosc1Oct 80
#define   CCosc2Oct 81
#define   CCLFO3Waveform 82
#define   CCeffectPot1 83
#define   CCeffectPot2  84
#define   CCeffectPot3  85
#define   CCeffectsMix  86
#define   CCLFO2Rate 87
#define   CCfilterenvLinLogSW 88
#define   CCampenvLinLogSW 89
#define   CCplayMode 90
#define   CCLFO1Waveform 91
#define   CCdumpCompleteSW 92
#define   CCdumpStartedSW 93
#define   CCfilterRes 94
#define   CCsyncSW 95
#define   CCchordHoldSW 96
#define   CCupperSW 97
#define   CClowerSW 98

#define   CCvcfATDepth 101
#define   CCosc2PulseLevel 102
#define   CCosc2SawLevel 103
#define   CCeffectparam3 104
#define   CCpitchRelease 105
#define   CCpitchAttack 106
#define   CCpitchSustain 107
#define   CCpitchDecay 108
#define   CCenv2_punch 109
#define   CCenv3_punch 110
#define   CCenv1_punch 111
#define   CCenv2_env3_adsr 112
#define   CCdualDetune 113
#define   CCunisonDetune 114
#define   CCarpStartStop 115
#define   CCarpLatch 116
#define   CCarpMode 117
#define   CCarpRange 118

#define   CCallnotesoff 123//Panic button